/**
 * Product domain types.
 *
 * Mirrors the `products` table in Supabase (see docs/database.md).
 * These types are the single source of truth for product shapes across
 * services, hooks, and components. Keep them in sync with the DB schema —
 * do not add fields here that don't exist as columns.
 */

/**
 * A product row as stored in and returned from Supabase.
 */
export interface Product {
  id: string;
  sku: string;
  barcode: string | null;
  product_name: string;
  category_id: string | null;
  supplier_id: string | null;
  warehouse_id: string | null;
  location: string | null;
  current_stock: number;
  minimum_stock: number;
  unit: string;
  description: string | null;
  image_url: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Payload for creating a new product.
 *
 * `id`, `created_at`, and `updated_at` are generated by the database.
 * `sku` is generated by a PostgreSQL BEFORE INSERT trigger
 * (see migration: products_sku_seq / generate_product_sku) and must
 * never be supplied by callers — it is intentionally omitted here.
 * Columns with DB defaults (`current_stock`, `minimum_stock`, `unit`,
 * `active`) are optional here since Supabase will fill them in if omitted.
 */
export interface CreateProductInput {
  product_name: string;
  barcode?: string | null;
  category_id?: string | null;
  supplier_id?: string | null;
  warehouse_id?: string | null;
  location?: string | null;
  current_stock?: number;
  minimum_stock?: number;
  unit?: string;
  description?: string | null;
  image_url?: string | null;
  active?: boolean;
}

/**
 * Payload for updating an existing product.
 *
 * `id` identifies the row to update; every other field is optional so
 * callers can send partial updates (e.g. just `current_stock`). `sku`
 * is intentionally excluded — SKUs are immutable once generated.
 */
export interface UpdateProductInput extends Partial<CreateProductInput> {
  id: string;
}

/**
 * Columns that product lists can be sorted by.
 */
export type ProductSortField =
  | "product_name"
  | "sku"
  | "current_stock"
  | "created_at"
  | "updated_at";

/**
 * Sort direction, reusable by any other sortable list in the app.
 */
export type SortOrder = "asc" | "desc";

/**
 * Filter/search criteria used by the product list, search bar, and
 * filter panel. Kept generic enough to be reused by other list views
 * (e.g. dashboard low-stock widgets) that need a subset of these.
 */
export interface ProductFilters {
  search?: string;
  categoryId?: string;
  supplierId?: string;
  warehouseId?: string;
  active?: boolean;
  lowStockOnly?: boolean;
  sortBy?: ProductSortField;
  sortOrder?: SortOrder;
}

/**
 * Derived stock-level status for a product, used by badges/indicators
 * in the product list, details view, and dashboard widgets.
 */
export interface ProductStockStatus {
  productId: string;
  currentStock: number;
  minimumStock: number;
  status: "in_stock" | "low_stock" | "out_of_stock";
}