/**
 * Stock transaction domain types.
 *
 * Mirrors the `stock_transactions` table in Supabase (see docs/database.md).
 * These types are the single source of truth for stock transaction shapes
 * across services, hooks, and components. Keep them in sync with the DB
 * schema — do not add fields here that don't exist as columns.
 */

/**
 * Allowed values for `transaction_type`.
 */
export type TransactionType = "GOODS_RECEIPT" | "STOCK_OUT" | "ADJUSTMENT";

/**
 * A stock transaction row as stored in and returned from Supabase.
 */
export interface StockTransaction {
  id: string;
  product_id: string;
  transaction_type: TransactionType;
  quantity: number;
  reference_number: string | null;
  remarks: string | null;
  performed_by: string | null;
  created_at: string;
}

/**
 * Payload for creating a new stock transaction.
 *
 * `id` and `created_at` are generated by the database.
 */
export interface CreateStockTransactionInput {
  product_id: string;
  transaction_type: TransactionType;
  quantity: number;
  reference_number?: string | null;
  remarks?: string | null;
  performed_by?: string | null;
}

/**
 * Payload for updating an existing stock transaction.
 *
 * `id` identifies the row to update; every other field is optional so
 * callers can send partial updates (e.g. just `remarks`).
 */
export interface UpdateStockTransactionInput
  extends Partial<CreateStockTransactionInput> {
  id: string;
}

/**
 * Columns that stock transaction lists can be sorted by.
 */
export type TransactionSortField = "created_at" | "quantity" | "transaction_type";

/**
 * Sort direction, reusable by any other sortable list in the app.
 */
export type SortOrder = "asc" | "desc";

/**
 * Filter/search criteria used by the stock transaction list and any
 * filter panel built on top of it.
 */
export interface TransactionFilters {
  productId?: string;
  transactionType?: TransactionType;
  search?: string;
  dateFrom?: string;
  dateTo?: string;
  sortBy?: TransactionSortField;
  sortOrder?: SortOrder;
}