import { supabase } from "@/lib/supabase/client";
import type {
  Product,
  CreateProductInput,
  UpdateProductInput,
  ProductFilters,
} from "@/types/product";

const TABLE = "products";

/**
 * Wraps a Supabase error into a consistent, descriptive Error so callers
 * (hooks) don't need to know about PostgrestError shape.
 */
function toServiceError(action: string, message: string): Error {
  return new Error(`[products.service] Failed to ${action}: ${message}`);
}

/**
 * Fetch products, optionally filtered/sorted.
 *
 * `lowStockOnly` compares two columns (current_stock vs minimum_stock),
 * which PostgREST can't express as a simple column filter, so it's
 * applied client-side after the rest of the filters run in the query.
 */
export async function getProducts(
  filters?: ProductFilters
): Promise<Product[]> {
  let query = supabase.from(TABLE).select("*");

  if (filters?.search) {
    const term = filters.search.trim();
    if (term.length > 0) {
      query = query.or(
        `product_name.ilike.%${term}%,sku.ilike.%${term}%,barcode.ilike.%${term}%`
      );
    }
  }

  if (filters?.categoryId) {
    query = query.eq("category_id", filters.categoryId);
  }

  if (filters?.supplierId) {
    query = query.eq("supplier_id", filters.supplierId);
  }

  if (filters?.warehouseId) {
    query = query.eq("warehouse_id", filters.warehouseId);
  }

  if (typeof filters?.active === "boolean") {
    query = query.eq("active", filters.active);
  }

  const sortBy = filters?.sortBy ?? "created_at";
  const ascending = filters?.sortOrder === "asc";
  query = query.order(sortBy, { ascending });

  const { data, error } = await query;

  if (error) {
    throw toServiceError("fetch products", error.message);
  }

  const products = data ?? [];

  if (filters?.lowStockOnly) {
    return products.filter((p) => p.current_stock <= p.minimum_stock);
  }

  return products;
}

/**
 * Fetch a single product by id. Throws if it doesn't exist.
 */
export async function getProduct(id: string): Promise<Product> {
  const { data, error } = await supabase
    .from(TABLE)
    .select("*")
    .eq("id", id)
    .single();

  if (error) {
    throw toServiceError(`fetch product ${id}`, error.message);
  }

  if (!data) {
    throw toServiceError(`fetch product ${id}`, "Product not found");
  }

  return data;
}

/**
 * Create a new product.
 *
 * SKU is intentionally never sent — it is generated by the
 * `generate_product_sku` BEFORE INSERT trigger in Postgres
 * (sequence: products_sku_seq, format JL-000001). `CreateProductInput`
 * has no `sku` field, so there is nothing to strip here; the row
 * returned by `.select().single()` includes the DB-generated SKU.
 */
export async function createProduct(
  input: CreateProductInput
): Promise<Product> {
  const { data, error } = await supabase
    .from(TABLE)
    .insert(input)
    .select("*")
    .single();

  if (error) {
    throw toServiceError("create product", error.message);
  }

  return data;
}

/**
 * Update an existing product. Only the fields present on `input`
 * (besides `id`) are sent, so partial updates don't clobber other
 * columns. SKU is immutable and cannot be updated through this input.
 */
export async function updateProduct(
  input: UpdateProductInput
): Promise<Product> {
  const { id, ...rest } = input;

  const { data, error } = await supabase
    .from(TABLE)
    .update(rest)
    .eq("id", id)
    .select("*")
    .single();

  if (error) {
    throw toServiceError(`update product ${id}`, error.message);
  }

  return data;
}

/**
 * Delete a product by id.
 */
export async function deleteProduct(id: string): Promise<void> {
  const { error } = await supabase.from(TABLE).delete().eq("id", id);

  if (error) {
    throw toServiceError(`delete product ${id}`, error.message);
  }
}